//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyResX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EasyResXResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EasyResXResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyResX.EasyResXResources", typeof(EasyResXResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occured: {0}.
        /// </summary>
        internal static string ApplicationExceptionFormat {
            get {
                return ResourceManager.GetString("ApplicationExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Application error&quot;.
        /// </summary>
        internal static string ApplicationExceptionMessage {
            get {
                return ResourceManager.GetString("ApplicationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup of.
        /// </summary>
        internal static string BackupOfMessage {
            get {
                return ResourceManager.GetString("BackupOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package created
        ///.
        /// </summary>
        internal static string CreatePackageOk {
            get {
                return ResourceManager.GetString("CreatePackageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering.
        /// </summary>
        internal static string EnteringFolderMessage {
            get {
                return ResourceManager.GetString("EnteringFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid setting.
        /// </summary>
        internal static string InvalidSynchronizationModeMessage {
            get {
                return ResourceManager.GetString("InvalidSynchronizationModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keys added.
        /// </summary>
        internal static string KeysAddedMessage {
            get {
                return ResourceManager.GetString("KeysAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keys removed.
        /// </summary>
        internal static string KeysRemovedMessage {
            get {
                return ResourceManager.GetString("KeysRemovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load project first.
        /// </summary>
        internal static string LoadProjectExceptionMessage {
            get {
                return ResourceManager.GetString("LoadProjectExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a package to merge into the project.
        /// </summary>
        internal static string MergeFileDialogTitle {
            get {
                return ResourceManager.GetString("MergeFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge failed
        ///.
        /// </summary>
        internal static string MergePackageResultFail {
            get {
                return ResourceManager.GetString("MergePackageResultFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package merged successfully
        ///.
        /// </summary>
        internal static string MergePackageResultOk {
            get {
                return ResourceManager.GetString("MergePackageResultOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translator_package_{0}.zip.
        /// </summary>
        internal static string PackageFormat {
            get {
                return ResourceManager.GetString("PackageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string ProcessingMessage {
            get {
                return ResourceManager.GetString("ProcessingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READY.
        /// </summary>
        internal static string ReadyMessage {
            get {
                return ResourceManager.GetString("ReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save package file.
        /// </summary>
        internal static string SaveFileDlgCaption {
            get {
                return ResourceManager.GetString("SaveFileDlgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save operation failed.
        /// </summary>
        internal static string SaveFileDlgMessage {
            get {
                return ResourceManager.GetString("SaveFileDlgMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization completed.
        /// </summary>
        internal static string SynchronizationCompleteMessage {
            get {
                return ResourceManager.GetString("SynchronizationCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Unable to synchronize files.
        /// </summary>
        internal static string SynchronizingErrorMessage {
            get {
                return ResourceManager.GetString("SynchronizingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing file.
        /// </summary>
        internal static string SynchronizingFileMessage {
            get {
                return ResourceManager.GetString("SynchronizingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Unable to synchronize files.
        /// </summary>
        internal static string UnableToSynchronizeFilesMessage {
            get {
                return ResourceManager.GetString("UnableToSynchronizeFilesMessage", resourceCulture);
            }
        }
    }
}
